# fly.toml app configuration file generated for embedify on 2024-01-17T20:19:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "embedify"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
